name: Flatpak Flutter Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - flatpak/flutter-extension/*
      - .github/workflows/flatpak-flutter-extension.yaml
  schedule:
    - cron: "17 5 * * 6"

env:
  SDK_VERSION: "24.08"

jobs:
  build_extension:
    name: Build flatpak runtime extension
    environment: flatpak
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

        include:
          - arch: x86_64
            runsOn: ubuntu-latest
            yqArch: amd64
          - arch: aarch64
            runsOn: ubuntu-24.04-arm
            yqArch: arm64
    runs-on: ${{ matrix.runsOn }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Install yq
        run: |
          set -eo pipefail
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${{ matrix.yqArch }} -O /usr/bin/yq
          chmod +x /usr/bin/yq
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Configure Flatpak runtime version
        run: >-
          yq e -i
          '.branch = strenv(SDK_VERSION) | .runtime-version = strenv(SDK_VERSION)'
          flatpak/flutter-extension/org.freedesktop.Sdk.Extension.flutter.yaml
      - name: Import GPG key
        run: echo '${{ secrets.GPG_KEY }}' | gpg --import
      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.freedesktop.Sdk.Extension.flutter_${{ env.SDK_VERSION }}_${{ matrix.arch }}.flatpak
          manifest-path: flatpak/flutter-extension/org.freedesktop.Sdk.Extension.flutter.yaml
          gpg-sign: ${{ secrets.GPG_KEY_ID }}
          verbose: true
          cache: false
          upload-artifact: false
          arch: ${{ matrix.arch }}
      - name: Upload flatpak bundle
        uses: actions/upload-artifact@v5
        with:
          name: flatpak-bundle-${{ matrix.arch }}
          path: org.freedesktop.Sdk.Extension.flutter_${{ env.SDK_VERSION }}_${{ matrix.arch }}.flatpak
          compression-level: 0
          if-no-files-found: error
          retention-days: 1
      - name: Delete GPG key
        if: always()
        continue-on-error: true
        run: gpg --batch --yes --delete-secret-keys '${{ secrets.GPG_KEY_ID }}'

  release_extension:
    name: Release flatpak runtime extension
    runs-on: ubuntu-latest
    needs:
      - build_extension
    environment: flatpak
    permissions:
      contents: write
    steps:
      - name: Download flatpak bundles
        uses: actions/download-artifact@v6
        with:
          path: bundles
          pattern: flatpak-bundle-*
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: flatpak-flutter-extension/${{ env.SDK_VERSION }}
          name: Flatpak Flutter Extension - ${{ env.SDK_VERSION }}
          target_commitish: ${{ github.sha }}
          files: bundles/flatpak-bundle-*/*.flatpak
          fail_on_unmatched_files: true
          make_latest: false
